hpcc-systems/eclide

comms/Attribute.cpp
comms/DiskAttribute.cpp
comms/ModFileAttribute.cpp

IDE=538 Loading mod files with large attributes is prohibitively slow
Fixed IDE-538

IDE=538 Loading mod files with large attributes is prohibitively slow

---

amt/AMT.cpp
eclide/QueryBuilder.cpp

IDE-512 Default BugTrap window to advanced mode

---

eclide/BookmarksFrame.cpp
eclide/BookmarksFrame.h
eclide/BookmarksView.cpp
eclide/BookmarksView.h
eclide/ChildAttributeFrame.cpp
eclide/ChildAttributeFrame.h
eclide/ChildBuilderFrame.cpp
eclide/ChildBuilderFrame.h
eclide/EclDlgAttribute.cpp
eclide/EclDlgBuilder.cpp
eclide/EclDlgBuilder.h
eclide/GraphView.cpp
eclide/GraphView3.cpp
eclide/mainfrm.cpp
eclide/mainfrm.h

IDE-534P Bookmarks not working on local files

---

docs/LanguageColor.xml
eclide/EclDlgBuilder.cpp
eclide/EclDlgBuilder.h
en_us/en_us.rc
en_us/resource.h
wlib/PreferenceDlg.cpp
wlib/PreferenceDlg.h
wlib/SourceView.cpp
wlib/SourceView.h

IDE-522 TextEditor - Background color to denote the target

---

comms/AttributeType.cpp
wlib/AttrListDlg.cpp

IDE-539  Support file extension in mod import

---

eclide/mainfrm.cpp
eclide/mainfrm.h
en_us/en_us.rc
en_us/resource.h

IDE-122P Add additional tab control for Builder Window and Workunits

---

comms/Dali.cpp
comms/Dali.h
comms/LocalWorkunit.cpp
comms/Workunit.cpp
comms/Workunit.h
comms/XGMMLWorkunit.cpp
eclide/ChildBuilderFrame.cpp
eclide/ChildBuilderFrame.h
eclide/mainfrm.cpp
eclide/mainfrm.h

Double click a WU attempts to locates the attribute that created it.
Fixes IDE-561

IDE-561 Open WU locates attribute

---

CMakeLists.txt

Default to side by side install on major.minor updates.
Fixes IDE-580

IDE-580 Change install policy

---

eclide/RepositoryFrame.h
en_us/en_us.rc
wlib/RepositoryTreeNode.h
wlib/RepositoryView.cpp

Fixes IDE-579
Signed-off-by: dehilsterlexis david.dehilster@lexisnexis.com

IDE-579 Add Crtl+N to the Repository Tree Tab to create new attribute

---

wlib/AttrListDlg.cpp

IDE-585 Dedup attrs on mod file import

---

wlib/PreferenceDlg.cpp
wlib/SourceView.cpp

IDE-587 Scrolling sample text in Color Preferences changes element combo selection

---

amt/TreePairNode.cpp
eclide/RepositoryFrame.h
eclide/WorkunitFrame.h
eclide/WorkunitView.cpp
eclide/WorkunitView.h
en_us/en_us.rc
en_us/resource.h
wlib/DaliTreeNode.cpp
wlib/MultiTree.h
wlib/MultiTreeNode.h
wlib/RepositoryTreeNode.cpp
wlib/TreeNode.cpp
wlib/WorkspaceTreeNode.cpp

IDE-593 Folder icons don't open and close correctly

---

eclide/InsAttrDlg.cpp
wlib/LangRef.cpp
wlib/PreferenceDlg.cpp
wlib/SourceView.cpp
wlib/SourceView.h

IDE-599 Asterisks showing up in Type pulldown in Insert File

---

comms/Attribute.cpp
comms/Attribute.h
comms/AttributeType.cpp
comms/DiskAttribute.cpp
comms/DiskRepository.cpp
comms/ModFileAttribute.cpp
comms/ModFileRepository.cpp
comms/Repository.h
comms/RepositoryImpl.h
eclide/RepositoryFrame.h
en_us/en_us.rc
en_us/resource.h
wlib/RepositoryView.h

IDE-600 Change attribute type for local files

---

comms/AttributeImpl.h

IDE-603 Plugin + sibling folders

---

comms/AttributeImpl.h

The format matches the preference page.
Fixes IDE-553

IDE-553 Add WsWorkunits URL to external plugin call

---

en_us/en_us.rc

IDE-622 Submit Selected short cut not working

---

comms/Attribute.cpp
comms/Attribute.h
comms/AttributeHistory.cpp
comms/AttributeHistory.h
comms/DiskAttribute.cpp
comms/DiskAttributeHistory.cpp
comms/ModFileAttribute.cpp
comms/ModFileAttributeHistory.cpp
comms/ModuleHelper.cpp
comms/ModuleHelper.h
eclide/ChildAttributeFrame.cpp
eclide/HistoryView.cpp
wlib/RepositoryView.h
wlib/TreeNode.cpp

Regression caused by the displaying of file extensions.
Fixes IDE-620

IDE-620 Sync TOC Broken

---

comms/AttributeType.cpp
eclide/RepositoryFrame.h
wlib/LangRef.cpp
wlib/PreferenceDlg.cpp
wlib/RepositoryTreeNode.cpp

IDE-609 ECM attributes need to be treated as ESDL attributes

---

comms/AttributeImpl.h

IDE-611 Get ESDL executable working locally through a batch file

---

tabctrls/TabbedFrame.h

IDE-616 Single-letter NAMED outputs don't show letter

---

comms/Attribute.cpp
comms/Attribute.h
comms/AttributeImpl.h
comms/DiskAttribute.cpp
comms/ModFileAttribute.cpp
comms/ModFileRepository.cpp
comms/RepositoryImpl.h
eclide/ChildBuilderFrame.cpp
eclide/EclDlgAttribute.cpp
eclide/EclDlgBuilder.cpp

IDE-373 2 level KEL imports not working

---

comms/AttributeType.cpp
comms/AttributeType.h
comms/ModFileAttribute.cpp
comms/ModFileRepository.cpp
comms/Repository.cpp

IDE-594 Import of .DUD file from KEL fails and gives boost warning

---

comms/AttributeImpl.h

IDE-635 Pass password to batch files

---

eclide/RepositoryFrame.h
wlib/RepositoryView.cpp
wlib/RepositoryView.h

IDE-626 Add Del key to Repository to delete

---

eclide/RepositoryFrame.h

IDE-630 Remove code that blocks local directory context menu

---

en_us/en_us.rc

IDE-654 Add key word "Del" to the repository context menu

---

clib/global.cpp
clib/global.h
comms/EclCC.cpp

IDE-645 Ensure IDE works with 64bit client tools

---

comms/Attribute.cpp
comms/Attribute.h
comms/AttributeType.cpp
comms/AttributeType.h
comms/Dali.h
comms/DiskAttribute.cpp
comms/ModFileAttribute.cpp
comms/ModFileRepository.cpp
comms/Repository.h
comms/RepositoryImpl.h
comms/WorkspaceItem.cpp
comms/WorkspaceItem.h
eclide/ChildAttributeFrame.cpp
eclide/ChildBuilderFrame.cpp
eclide/ChildBuilderFrame.h
eclide/ChildFrame.cpp
eclide/ChildFrame.h
eclide/ChildGraphFrame.cpp
eclide/EclDlg.h
eclide/EclDlgAttribute.cpp
eclide/EclDlgAttribute.h
eclide/EclDlgBuilder.cpp
eclide/EclDlgBuilder.h
eclide/mainfrm.cpp
en_us/resource.h
wlib/PreferenceDlg.cpp
wlib/SourceView.cpp
wlib/SourceView.h

IDE-636 Add Publish item to Submit pulldown for ESDL

---

comms/AttributeImpl.h

fixed Ensure batch file accessibility from clienttools/IDEPlugins/ESDL

IDE-655 Ensure batch file accessibility from clienttools/IDEPlugins/ESDL

---

comms/Attribute.cpp
comms/Attribute.h
comms/AttributeImpl.h
comms/AttributeType.cpp
comms/AttributeType.h
comms/DiskAttribute.cpp
comms/ModFileAttribute.cpp
comms/RepositoryImpl.h
eclide/ChildBuilderFrame.cpp
eclide/EclDlgAttribute.cpp
eclide/EclDlgBuilder.cpp
eclide/ResultView.cpp
eclide/ResultView.h
eclide/SummaryView.cpp
eclide/SummaryView.h

IDE-665 Show DESDL Details page on publish

---

comms/AttributeImpl.h
comms/EclCC.cpp
comms/EclCC.h

Add clienttools/IDEPlugins as a known plugin location.

IDE-670 Add new plugins location

---

eclide/ChildBuilderFrame.cpp
eclide/EclDlgBuilder.cpp

IDE-685 Publish in pulldown menu for ESDL build windows does not display output

---

comms/ModFileRepository.cpp

IDE-678 ESDL Publish and Generate ECL fail from nested folder in local repository

---

eclide/ChildBuilderFrame.cpp

IDE-692 Opening existing WU causes crash

---

comms/RepositoryImpl.h
wlib/LangRef.h
wlib/SourceView.cpp

IDE-681 IDE autocomplete shows duplicate files

---

comms/Attribute.cpp
comms/DiskAttribute.cpp
comms/ModFileAttribute.cpp
eclide/ChildBuilderFrame.cpp
eclide/ChildBuilderFrame.h
eclide/mainfrm.cpp

IDE-700 IDE crashes when opening up an local file

---

comms/RepositoryImpl.h
eclide/mainfrm.cpp
eclide/mainfrm.h
en_us/en_us.rc

Do the following for the upper left "Open Source" submenu item: change description to say "attribute", only display when not local, add warning if file not found.
Fixed IDE-702

IDE-702 Change open source behavior and display

---

comms/AttributeImpl.h
comms/AttributeType.cpp
eclide/ChildBuilderFrame.cpp
eclide/EclDlgBuilder.cpp
eclide/RepositoryFrame.h

IDE-674 ESDL files with *.ECM extension should be treated as ESDL code

---

eclide/EclDlgBuilder.cpp

IDE-679 ESDL Editor window should not offer Target choice

---

eclide/EclDlgBuilder.cpp

To assist folks migrating from remote to local.

IDE-705 Display qualified label in editor tab

---

comms/WorkspaceItem.cpp

IDE-707 Opening empty Default workspace folder causes hang

---

en_us/en_us.rc
en_us/resource.h
wlib/EclCommand.h
wlib/PreferenceDlg.cpp
wlib/PreferenceDlg.h
wlib/SourceView.cpp

IDE-713 Show/Hide white-space characters

---

wlib/SourceView.cpp

IDE-712 Tab sizes being set incorrectly

---

eclide/RepositoryFrame.h
wlib/ShellContextMenu.cpp

IDE-662 Add git context menu for folders and files

---

comms/DiskRepository.cpp

This solution is the fastest I found and also does work with UTF-8 files with the findstr "p" or printable character switch on (which speeds up the search on big directories).

IDE-708 Searching local repository 10 times slower than mySQL repository

---

.gitmodules
EclEditor/CMakeLists.txt
cmake/Modules/Externals.cmake
eclide/SourceDataView.cpp
wlib/SourceView.cpp
wlib/SourceView.h
wlib/scite.h
wtlex/atlscintilla.h

IDE-711 Update Scintilla to 3.7.6

---

eclide/mainfrm.cpp

IDE-683 Using IDE with local repository has some differences which are not desirable

---

amt/MainFrm2.cpp
amt/MainFrm2.h

IDE-721 No colorization in AMT attribute windows

---

comms/DiskRepository.cpp
comms/Repository.cpp
comms/RepositoryImpl.h

IDE-736 Local repo has invalid config folder.

---

comms/DiskAttribute.cpp
comms/ModFileAttribute.cpp

IDE-724 some Tabs in ECL IDE are missing the label

---

wlib/RepositoryTreeNode.cpp
wlib/RepositoryTreeNode.h

ECL IDE Find Repository "Refresh" duplicates attributes

---

wlib/LangRef.cpp

IDE-415 Library and Locked background color unchangeable

---

eclide/RepositoryFrame.h
en_us/en_us.rc
en_us/resource.h
wlib/RepositoryView.h

IDE-716 "Collapse All" option for tree

---

comms/ModFileRepository.cpp
comms/RepositoryImpl.h
comms/WorkspaceItem.cpp
comms/WorkspaceItem.h
eclide/ChildBuilderFrame.cpp

IDE-765 Multiple tabs opened when opened from repository search

---

eclide/mainfrm.cpp

IDE-768 Double click attribute search locally should open builder window

---

eclide/WtlMDIChildFrame.h

IDE-777 Save not working for files

---

eclide/ChildBuilderFrame.cpp

IDE-783 Unable to open multiple blank builder windows

---

eclide/EclDlgBuilder.cpp

IDE-755 Remove "Local" target in the builder window for local attributes

---

comms/EclCC.cpp

Some errors (case sensitive) are making it through the error test.

IDE-750 Prevent submission of archives with errors

---

wlib/RepositoryTreeNode.cpp

IDE-788 Wrong folder color when selecting top level repository

---

eclide/BookmarksView.cpp

IDE-799 Existing bookmark descriptions not updating when file is saved

---

eclide/BookmarksView.cpp

IDE-800 Crash when double-click on empty line in bookmark tab

---

comms/Cluster.cpp
comms/Cluster.h
comms/Topology.cpp
comms/Topology.h
comms/comms.h
comms/stdafx.h
eclide/ChildBuilderFrame.cpp
eclide/EclDlgBuilder.cpp
wlib/Combo.cpp
wlib/Combo.h
wlib/RepositoryTreeNode.cpp
wlib/SourceView.cpp
wlib/SourceView.h

Default to roxie instead of hthor.
Removed unused code
Possible fix for GPF during workspace restoration

IDE-739 Default to roxie target cluster

---

docs/LanguageRefESDL.xml

IDE-717 ESDL hover-over samples need to be polished

---

eclide/ResultView.cpp

IDE-805 Trim ECL Watch URLs
Fixed IDE-805

IDE-805 Trim ECL Watch URLs

---

comms/AttributeType.cpp

IDE-802 File SaveAs should default to ECL

---

wlib/LangRef.cpp
wlib/PreferenceDlg.cpp

IDE-801 Default button in color preferences does not work

---

docs/LanguageRefECL.xml

IDE-758 Update lang ref xml to 7.0
Fixed IDE-758

IDE-758 Update lang ref xml to 7.0

---

wlib/SourceView.cpp

IDE-803 Language colors don't seem to work 100%

---

eclide/ResultView.cpp

IDE-815 Graphs Tab fails to load

---

comms/Account.cpp
comms/Account.h
wlib/LoginDlg.cpp
wlib/LoginDlg.h

IDE-660 ECL IDE should allow for an expired password to be changed

IDE-660 ECL IDE should allow for an expired password to be changed

---

comms/EclCC.cpp
comms/EclCC.h
comms/EclMeta.cpp
comms/EclMeta.h
eclide/EclDlgBuilder.cpp

IDE-825 Move meta initialization into CreateIModule/Attribute

---

comms/Autoupdate.cpp
comms/Autoupdate.h
wlib/HtmlView.h

IDE-850 Perform DNS Lookup on all embedded web pages

---

eclide/RepositoryFrame.h
en_us/en_us.rc
en_us/resource.h
wlib/AttrListDlg.cpp
wlib/AttrListDlg.h
wlib/RepositoryView.h

IDE-856 Combine ECL files to a MOD file using right click menu in the repository

---

clib/SAXHandlersBase.h
comms/EclCC.cpp
comms/EclCC.h
comms/EclMeta.cpp
comms/EclMeta.h
comms/gSoapUtil.h
wlib/LangRef.cpp
wlib/SourceView.cpp

Added #define NSOAP_DEBUG for future use to debug soap messaging.

IDE-879 Add Tooltip for functions from metadata

---

README.md

IDE-895 Update prerequisites in README.md

---

CMakeLists.txt

IDE-897 Install package is missing MFC DLLs

---

eclide/EclDlgAttribute.cpp
eclide/EclDlgAttribute.h

IDE-893 Add Unfold and Fold to the attribute windows

---

comms/EclMeta.cpp
comms/EclMeta.h

IDE crash edge condition when parsing meta data on a specific file

---

eclide/ChildAttributeFrame.cpp
eclide/ChildBuilderFrame.cpp
en_us/en_us.rc

IDE-888 Hot Keys for fold all/ unfold all

---

eclide/ChildBuilderFrame.cpp

IDE-908 Opening local file opens duplicate

---

comms/EclMeta.cpp

IDE-912 Autocomplete doesn't

---

comms/EclMeta.cpp
comms/EclMeta.h

IDE-914 Add functions to autocomplete

---

comms/Attribute.cpp
comms/Attribute.h
comms/DiskAttribute.cpp
comms/DiskRepository.cpp
comms/ModFileAttribute.cpp
eclide/EclDlg.h
eclide/EclDlgBuilder.cpp
wlib/SourceView.cpp
wlib/SourceView.h

Was missing logic for user-marked deletions.

IDE-903 Crash on file deletion in repository tree

---

EclEditor/LexKEL.cxx

IDE-945 Rename function in LexKEL

---

clib/global.cpp
clib/global.h
comms/Attribute.cpp
comms/AttributeImpl.h
comms/EclCC.cpp
comms/EclCC.h
eclide/ChildBuilderFrame.cpp
eclide/EclDlg.h
eclide/EclDlgAttribute.cpp
eclide/EclDlgAttribute.h
eclide/EclDlgBuilder.cpp
eclide/EclDlgBuilder.h
en_us/en_us.rc
en_us/resource.h

@GordonSmith for review. I want to wait a week so that Brenton has time to test with with KEL.

IDE-602 KEL Syntax Check v Generate

---

comms/DiskRepository.cpp
comms/ModFileRepository.cpp
comms/Repository.cpp
comms/Repository.h
en_us/en_us.rc
wlib/RepositoryView.h

IDE-956 IDE "Move File" only works for one file at a time

---

eclide/EclDlgBuilder.cpp
eclide/EclDlgBuilder.h

IDE-791 Query scheduling feature not working

---

amt/AMT.cpp
eclide/QueryBuilder.cpp

IDE-918 Link to the product support site is broken

---

eclide/BookmarksFrame.cpp
eclide/BookmarksView.cpp
eclide/BookmarksView.h
eclide/mainfrm.cpp

IDE-970 Bookmark warning on ECLIDE 7.10.x

---

comms/WorkspaceItem.cpp
eclide/ChildBuilderFrame.cpp

IDE-971 Workspace not loading

---

eclide/ChildFrame.cpp

IDE-979 Workspaces files not saving attribute file info correctly

---

.gitignore
comms/EclCC.cpp
comms/Repository.cpp
eclide/mainfrm.cpp
eclide/mainfrm.h
wlib/PreferenceDlg.h

* Reduce connection timeout for initial WsAttributes test
* Auto remove WsAttributes from preferences
* Cache current eclcc version for duration of session
* Refresh workspace on background thread

IDE-980 Login Performance Improvements

---

eclide/RepositoryFilterView.cpp

IDE-975 Gray out items in Find Repository panel for local repositories

---

eclide/mainfrm.cpp

IDE-988:  Typo "Prefrences"

---

clib/Util.cpp
clib/Util.h

IDE-1001 Get Locale missing country code suffix

---

eclide/ChildBuilderFrame.cpp

IDE-989 Submit Context menu intermittently disabled

---

CMakeLists.txt

IDE-1006  Update code signing time server URL

---

CMakeLists.txt

@GordonSmith review again. Thanks

IDE-1006 Updat code signing time server URL

---

comms/WorkspaceItem.cpp
comms/WorkspaceItem.h
eclide/mainfrm.cpp
wlib/WorkspaceTreeNode.cpp

Also fixed a related label problem revealed with the crash fix.

IDE-1002 Fixed workspace crash

---

.gitmodules

IDE-1009 Patch CEF Source Location

---

comms/EclMeta.cpp

IDE-1011 Unexpected Meta causes crash

---

eclide/mainfrm.cpp
eclide/mainfrm.h

IDE-1007 Fixed quick menu crash

---

.gitignore
.vscode/settings.json
CMakeLists.txt
en_us/CMakeLists.txt

IDE-1025 Copy development dependencies during build

---

comms/EclCC.cpp

Signed-off-by: David de Hilster <dehilsterlexis>

IDE-1049 Duplicate entry in clienttools pulldown for compiler

---

comms/EclCC.cpp

IDE-1057 Clients tools not loading on open without override

---

eclide/mainfrm.cpp

IDE-1058 Tooltip for status bar elements

---

eclide/ChildAttributeFrame.cpp

IDE-974 Opening read-only files from a Find (Repository) incorrectly

---

clib/SeisintDatasetSAXHandler.h
eclide/ResultView.cpp

IDE-1076 Whitespace not shown in result viewer

---

comms/EclCC.cpp
comms/EclCC.h
wlib/PreferenceDlg.cpp

IDE-1068 Repository does not refresh after adding ECL Folder in Compiler Preferences

---

CMakeLists.txt
CMakePresets.json
vcpkg-configuration.json
vcpkg.json

Improve the build system by adding cmake presets and vcpkg configuration
Gordon Smith <GordonJSmith@gmail.com>

IDE-1130 Add cmake presets and vcpkg configuration files

---

comms/Dali.cpp

Forgot to add the protect value to the request.

IDE-1132 Unprotect menu item in WU context menu not working

---

comms/Dali.cpp
comms/Dali.h
eclide/ChildBuilderFrame.cpp
eclide/EclDlgBuilder.cpp
eclide/EclDlgBuilder.h
eclide/ResultView.cpp
eclide/ResultView.h
wlib/EclExec.cpp
wlib/EclExec.h

Could be using lookup or github refs

IDE-1145 Submit (no archive) should skip local syntax check
