comms/Attribute.cpp, comms/Attribute.h, comms/DiskAttribute.cpp, comms/Migration.cpp, comms/Migration.h, comms/ModFileAttribute.cpp, wlib/AttrListDlg.cpp
* Adding support for files in the 300->600MB range.
* Keep ECL in "narrow" strings for as long as possible.
* Judicious clearing of memory structes as the core content is passed around.
* Eliminate string copies where possible.
* Stream from file.
Fixes IDE-538
=> IDE-538 Import large MOD files, fail

EclEditor/CMakeLists.txt
=> IDE-571 Wrong path for LexSALT.cxx in CMakeLists

docs/LanguageColor.xml
=> IDE-577 Duplicate element names in Preferences > Colors tab

EclEditor/CMakeLists.txt
Wrong path in CMakeLists.txt
Fixes IDE-621
=> IDE-621 IDE Failing to build

comms/AttributeImpl.h
Hide message (safer and may be useful having a ecl.bat hook later).
Fixes IDE-436
=> IDE-436 Erroneous warning "Plugin not found - ecl.bat"

clib/PersistMap.cpp, comms/Workspace.cpp, comms/WorkspaceItem.cpp, comms/WorkspaceItem.h
Serialization fails when ECL contains Unicode characters.
Force workspace items to char* + UTF8 for serialization
Fixes IDE-629
=> IDE-629 Workspace serialization + Unicode ECL

comms/AttributeImpl.h
=> IDE-634 Add double quotes to Username and Workunit when passing to batch files

CMakeLists.txt
This can be verified during ECLIDE installation.
Also there are additional docs/*.xml files for ECL code coloring. These file are installed to bin directory. Previous LanguageColor.xml and LanguageReference.xml may not be required anymore. But I am not sure so I still include them.
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexi.com> 
@dehilsterlexis please review the change.
@JamesDeFabia  Please help testing. The private build: http://10.240.32.242/builds/custom/JIRA/IDE-658/hpccsystems-eclide-community_6.4.0-rc1Windows-i386.exe
=> IDE-658 Set real version for start menu

comms/DropZone.cpp
Missing TpMachine info causes crash.
=> IDE-680 IDE Crash when dropzone is misconfigured

comms/Workspace.cpp
=> IDE-672 Misspelling of "failed" as "faileed" in Workspace warning message

comms/Dali.cpp, comms/gSoapUtil.h
ESP defaults to a max of 8MB, added flag to override.
=> IDE-704 Submitting large ECL/Archive fails

wlib/SourceView.cpp
In my IDE tab width is set to be 2 spaces. This works fine for any new code, but if I open an attribute with existing tabs, the tabs in it have width equal to a single space.
=> IDE-703 Editor ignores tab width

clib/cmdProcess.cpp
Added extra modifiers to make it harder for accidental triggering.
=> IDE-696 Change hot keys for CMD Process logging

wlib/LangRef.cpp
=> IDE-725 No syntax colorization in opened dll files

EclLib/DefinitionParser.cpp, EclLib/EclLib.cpp, EclLib/EclParser.cpp, EclLib/VersionParser.cpp, EclLib/VersionParser.h, EclLib/ecl_grammar.cpp, EclLib/stdafx.h, comms/Account.cpp, comms/EclCC.cpp, comms/SMCVersion.cpp, comms/SMCVersion.h, wlib/AboutDlg.cpp, wlib/SourceView.cpp
Possible heap corruption string is changed en route into boost::format.
Disabled excess logging in debug mode.
=> IDE-734 Possible crash reading version information

eclide/EclDlgBuilder.cpp
@GordonSmith I used spy++ to see if there were any changes in window pointers but never found them to be different. I used a logical check instead which I have tested with multiple checks on multiple windows at the same time.
=> IDE-625 Extraneous message on Syntax Check

comms/Topology.cpp, eclide/EclDlgBuilder.cpp
Rollback IDE-786
Remove "Local" from target options
Fixes IDE-786
=> IDE-786 Missing options on builder window

wlib/EclCommand.h
=> IDE-793 IDE-786 change blocks the check syntax button

comms/EclMeta.cpp, wlib/EclCommand.h
Normalize directory path from metadata. This used to be the third part of the sprint for F12 and better tooltip information. That has been pushed to IDE-807.
=> IDE-731 Normalize directory path from metadata

CMakeLists.txt
Signed-off-by: Godson Fortil <FortGo01@LexisNexisRisk.Com>
=> HPCC-21705 ECLIDE build fails with 7.0.22 branch.

EclEditor/LexECL.cxx
=> IDE-866 Fields named "TYPE" cause collapse to function incorrectly

wlib/RepositoryView.cpp
=> IDE-896 Repository Window word wheel inadvertently takes 'n' as Ctrl-N

wlib/HtmlChromiumView.cpp
Timing issue when "Navigate" is called too soon.
=> IDE-900 Crash viewing "compiled" query

wlib/LangRef.cpp
ECLLIB files should use the ECL lexer.
=> IDE-930 Opening ecllib file crashes IDE

wlib/LangRef.cpp
This should have been caught in a more thorough test of IDE-930.
=> IDE_931 IDE Crashes when workspace ecllib file is open

clib/logger.cpp
@GordonSmith for review
It didn't match: logger.h
```
enum LEVEL
{
LEVEL_FINEST = 0,
LEVEL_FINER, 
LEVEL_FINE, 
LEVEL_CONFIG,
LEVEL_DEBUG,
LEVEL_INFO,
LEVEL_WARNING, 
LEVEL_SEVERE
};
```
=> IDE-953 _DBGLOG message for LEVEL_INFO displaying "WARNING" not "INFO"

version.cmake
Remove point version < 66 restriction as it only applied to old WXI installer.
=> IDE-984 Remove version limitation

CMakeLists.txt
We experience a lots of signtool error "The specified timestamp server either could not be reached".
Thanks to Todd Leonard it seems http://timestamp.digicert.com with "/tr" is more stable.
The reference: https://knowledge.digicert.com/solution/SO912.html
We manually tested the setting and it run very well.
This fix should be applied to 7.12.x, 7.10.x and 7.8.x and master
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexis.com>
@GordonSmith  please review
=> IDE-1013 change timestamp URL to http://timestamp.digicert.com

comms/EclMeta.cpp
=> IDE-1018 RF_Classification crashes ECL IDE on load

CMakeLists.txt
The latest signtool from Windows SDK requests providing digest algorithm explicitly. The "SHA256" is commended.
I remove "^M" which is the reason that the whole file is updated.
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexis.com>
=> IDE-1052 add digest algorithm "sha256" explicitly for signtool

clib/UnicodeFile.cpp, clib/UnicodeFile.h
m_encoding was not being set during save
Remove ASCII support (replace with UTF8 + no BOM)
=> IDE-1065 Unicode file support regression

CMakeLists.txt
Force Clienttools package to x86_64
Signed off by [xiaoming.wang@lexisnexisrisk.com](mailto:xiaoming.wang@lexisnexisrisk.com)
@GordonSmith please review
=> HPCC-27534 enable building with 64bit Clienttools

CMakeLists.txt
Add a CMake flag CT_ARCH.
If this flag set to "i386" 32bit Clienttools will be used to build ECLIDE. The default is  64bit Clienttools.
Also remove hard-coded Clienttools installation location which will prevent 64bit Clienttools conversion and reboot prompt in ECLIDE installation.
=> Support ECLIDE build with  64bit Clienttools
